database:
  host: "db"
  user: "user_test"
  password: "password_test"
  port: "5432"
  name: "testdb"
  sslmode: "disable"

app:
  name: "test_app_name"
  url: "http://localhost:8182"
  http:
    port: 8182
  grpc:
    port: 50051
    service:
      file_service: file_service:50052
  verification_url: "verify-email?"
  auth_url: "http://localhost:8181"

redis:
  address: "redis"
  port: "6379"
  client_name: "auth_service_test"
  password: "password_test"

nats:
  protocol: "nats"
  address: "nats"
  port: "4221"
  credential:
    user: "user_test"
    password: "password_test"
  connection_name: "user_service_conn_test"
  timeout: 10

jetstream:
  stream: 
    name: "notification_stream_test"
    description: "this is notification stream"
  subject:
    global: "test_notif.>"
    mail: "test_notif.email"

server:
  cors:
    allow_origins: "*"
    allow_methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    allow_headers: "Content-Type, Authorization, X-Requested-With, X-CSRF-Token, Accept, Origin, Cache-Control, X-File-Name, X-File-Type, X-File-Size"
    expose_headers: "Content-Length, Content-Range"
    max_age: 86400
    allow_credential: true
