database:
  host: "db"
  user: "daffaputra"
  password: "password"
  port: "5432"
  name: "dropboks"
  sslmode: "disable"

app:
  name: "dropboks"
  grpc:
    port: 50051
  http:
    port: 80

server:
  cors:
    allow_origins: "*"
    allow_methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    allow_headers: "Content-Type, Authorization, X-Requested-With, X-CSRF-Token, Accept, Origin, Cache-Control, X-File-Name, X-File-Type, X-File-Size"
    expose_headers: "Content-Length, Content-Range"
    max_age: 86400
    allow_credential: true
